### ISSUE TITLE
After creating tag based on template the tag is not shown in GTM

### ISSUE THREAD

**Issue by sschurink** [facebookincubator/ConversionsAPI-Tag-for-GoogleTagManager#1]
I uploaded the template and tried to create a tag with a testcode, started testing the GTM setup, so far so good.

I wanted to finalize the setup by removing the testcode from the testfield. But the whole new tag created,  based on this template, is not te be found. I can only edit the template. 
I assume that the tag is somewhere in the GTM system as the data is still arriving in the facebook test environment.

Can you confirm this is also happening on your part?

**Comment by HeyMultiverse** [comment]
The Tag is completely operated on GTM portal, and we don't have any control over it. This is just the template –– after adding this to your workspace you might want to create a new Tag out of this. In that new tag you create, you can decide to add/remove test_event_code, which is optional argument anyways. If you plan to add test_event_code, you can verify it against our [testing tool](https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api#testEvents).
