### ISSUE TITLE
Instructions not available

### ISSUE THREAD

**Issue by denikatsman** [facebookincubator/ConversionsAPI-Tag-for-GoogleTagManager#2]
Hello,

Really appreciate the work you have put into this. Could you please make the instructions available again? Seems like they have been taken down from the Facebook developers website.

Thanks.

**Comment by HeyMultiverse** [comment]
Hello @denikatsman, Thanks for bringing this to our attention. Please find the instructions in the docs [here](https://www.facebook.com/business/help/702509907046774) and let us know if you have any questions. At this time, we are only having instructions in English and will support other locales soon.
